### ISSUE TITLE
TypeError: Cannot read property '$set' of undefined

### ISSUE THREAD

**Issue by sabirahmed121** [YuriGor/mongoose-slug-updater#23]
Running into this issue when using
`model.create(item)
`
_TypeError: Cannot read property '$set' of undefined
    at model.Query.onUpdate (/Users/sabir/React/cyber-rwanda/website/api/node_modules/mongoose-slug-updater/lib/slug-generator.js:158:13)
    at model.Query.<anonymous> (/Users/sabir/React/cyber-rwanda/website/api/node_modules/mongoose-slug-updater/lib/slug-generator.js:150:31)_

This is particularly happening in a model which does not use slug.
I've tried removing the plugin and it works fine without it.
The only relation it has to slug is that it contains an Object reference to a Model which has a slug.
Couldn't figure out why the plugin is called in a model which does not implement it.

Thanks for the awesome plugin

**Comment by sabirahmed121** [comment]
Ok after fiddling around a little I realize this model uses another plugin called "mongoose-sequence"
I removed that plugin and the issue goes away.

_**_Conclusion:_**_
_mongoose-slug-updater doesn't play well with "mongoose-sequence" plugin._
